services:
  frontend:
    image: nginx:alpine
    container_name: home_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./docker/frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    healthcheck:
      test: curl -f http://localhost/
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 5s
      start_interval: 5s

  backend:
    image: node:24-slim
    container_name: home_backend
    working_dir: /app
    volumes:
      - ./backend:/app:ro
    command: yarn start:prod
    env_file:
      - docker/backend/env
    environment:
      NODE_ENV: production
      PORT: 4000
    expose:
      - 4000
    restart: always
    healthcheck:
      test: ["CMD", "bash", "/app/scripts/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 5s
      start_interval: 5s

networks:
  default:
    external: true
    name: apps
